name: CI

on: [push, pull_request]

jobs:
  test:
    name: Run functional & unit tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/checkout@v1
      - name: install dependencies, then check for lint errors and run tests
        run: |
          yarn install
          yarn lint
          yarn test
  publish:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith( github.ref, 'refs/tags/' )
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/checkout@v1
      - name: publish new version to npm
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: ./.github/publish.sh
